from enum import Enum


class CommandCodes:
    TEXT_MESSAGE = 0
    FIND_SUCCESSOR = 1
    RETURN_SUCCESSOR = 2
    SUCCESSOR_RESPONSE = 3
    PREDECESSOR_REQUEST = 4
    PREDECESSOR_RESPONSE = 5
    NOTIFY = 6
